In [2]:
import pandas as pd
import numpy as np

Creating a DataFrame

In [9]:
data = {
    'Name':['John','Ana','Peter','Linda'],
    'Age': [28,34,29,42],
    'City': ['New York','Paris',"Berlin",'London'],
    'Salary': [65000,70000,62000,85000]
    
}
df = pd.DataFrame(data)

In [10]:
df

    Name  Age      City  Salary
0   John   28  New York   65000
1    Ana   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [13]:
data_list = [
    ["Alice", 20, 85],
    ["Bob", 21, 90],
    ["Charlie", 19, 78],
    ["David", 22, 88]
]
df2 = pd.DataFrame(data_list)
columns = ['Name','Age','City','Salary']
df2 = pd.DataFrame(data_list,columns)

In [14]:
df2

              0   1   2
Name      Alice  20  85
Age         Bob  21  90
City    Charlie  19  78
Salary    David  22  88

Selection and Indexing of Columns

In [15]:
df2

              0   1   2
Name      Alice  20  85
Age         Bob  21  90
City    Charlie  19  78
Salary    David  22  88

In [16]:
df

    Name  Age      City  Salary
0   John   28  New York   65000
1    Ana   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [22]:
df[['Name','Age']]

    Name  Age
0   John   28
1    Ana   34
2  Peter   29
3  Linda   42

Creating New Columns

In [23]:
df['Designation'] = ['Doctor','Engineer','Pilot','Teacher']

In [24]:
df

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1    Ana   34     Paris   70000    Engineer
2  Peter   29    Berlin   62000       Pilot
3  Linda   42    London   85000     Teacher

Remove column

In [27]:
df.drop('Designation',axis=1,inplace=True)

In [28]:
df

    Name  Age      City  Salary
0   John   28  New York   65000
1    Ana   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [31]:
df.loc[1]

Name        Ana
Age          34
City      Paris
Salary    70000
Name: 1, dtype: object

Selecting subset of Rows and columm

In [36]:
df.loc[[0,1]][['City','Salary']]

       City  Salary
0  New York   65000
1     Paris   70000

In [37]:
df

    Name  Age      City  Salary
0   John   28  New York   65000
1    Ana   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [39]:
df.loc[[2,3]][['Name','Age']]

    Name  Age
2  Peter   29
3  Linda   42

Conditional Selection

In [40]:
# I want to see who's age is above 30

In [46]:
df[df['Age'] > 30]

    Name  Age    City  Salary
1    Ana   34   Paris   70000
3  Linda   42  London   85000

In [50]:
df[(df['Age']> 30) & (df['City']== "Paris")]

  Name  Age   City  Salary
1  Ana   34  Paris   70000