In [2]:
import pandas as pd
import numpy as np

In [6]:
data_list = [
    ["Alice",   20,    85,     np.nan],
    ["Bob",     np.nan,90,     "Delhi"],
    ["Charlie", 19,    np.nan, np.nan],
    ["David",   np.nan,np.nan, "Mumbai"],
    ["Emma",    22,    88,     np.nan],
    ["Frank",   np.nan,75,     "Pune"],
    ["Grace",   21,    np.nan, "Delhi"],
    ["Henry",   np.nan,np.nan, np.nan],
    ["Ivy",     23,    92,     "Bangalore"],
    ["Jack",    np.nan,np.nan, "Chennai"]
]

df = pd.DataFrame(data_list)

In [11]:
df

         0     1     2          3
0    Alice  20.0  85.0        NaN
1      Bob   NaN  90.0      Delhi
2  Charlie  19.0   NaN        NaN
3    David   NaN   NaN     Mumbai
4     Emma  22.0  88.0        NaN
5    Frank   NaN  75.0       Pune
6    Grace  21.0   NaN      Delhi
7    Henry   NaN   NaN        NaN
8      Ivy  23.0  92.0  Bangalore
9     Jack   NaN   NaN    Chennai

In [12]:
df.isna()

       0      1      2      3
0  False  False  False   True
1  False   True  False  False
2  False  False   True   True
3  False   True   True  False
4  False  False  False   True
5  False   True  False  False
6  False  False   True  False
7  False   True   True   True
8  False  False  False  False
9  False   True   True  False

In [13]:
df.isna().sum()

0    0
1    5
2    5
3    4
dtype: int64

In [14]:
df.isna().any()

0    False
1     True
2     True
3     True
dtype: bool

Removing Missing Data

In [15]:
df

         0     1     2          3
0    Alice  20.0  85.0        NaN
1      Bob   NaN  90.0      Delhi
2  Charlie  19.0   NaN        NaN
3    David   NaN   NaN     Mumbai
4     Emma  22.0  88.0        NaN
5    Frank   NaN  75.0       Pune
6    Grace  21.0   NaN      Delhi
7    Henry   NaN   NaN        NaN
8      Ivy  23.0  92.0  Bangalore
9     Jack   NaN   NaN    Chennai

In [16]:
df.dropna()

     0     1     2          3
8  Ivy  23.0  92.0  Bangalore

In [19]:
df.dropna(thresh=3)

       0     1     2          3
0  Alice  20.0  85.0        NaN
1    Bob   NaN  90.0      Delhi
4   Emma  22.0  88.0        NaN
5  Frank   NaN  75.0       Pune
6  Grace  21.0   NaN      Delhi
8    Ivy  23.0  92.0  Bangalore

Filling the missing Data

In [20]:
df

         0     1     2          3
0    Alice  20.0  85.0        NaN
1      Bob   NaN  90.0      Delhi
2  Charlie  19.0   NaN        NaN
3    David   NaN   NaN     Mumbai
4     Emma  22.0  88.0        NaN
5    Frank   NaN  75.0       Pune
6    Grace  21.0   NaN      Delhi
7    Henry   NaN   NaN        NaN
8      Ivy  23.0  92.0  Bangalore
9     Jack   NaN   NaN    Chennai

In [21]:
df.fillna(0)

         0     1     2          3
0    Alice  20.0  85.0          0
1      Bob   0.0  90.0      Delhi
2  Charlie  19.0   0.0          0
3    David   0.0   0.0     Mumbai
4     Emma  22.0  88.0          0
5    Frank   0.0  75.0       Pune
6    Grace  21.0   0.0      Delhi
7    Henry   0.0   0.0          0
8      Ivy  23.0  92.0  Bangalore
9     Jack   0.0   0.0    Chennai

In [22]:
df

         0     1     2          3
0    Alice  20.0  85.0        NaN
1      Bob   NaN  90.0      Delhi
2  Charlie  19.0   NaN        NaN
3    David   NaN   NaN     Mumbai
4     Emma  22.0  88.0        NaN
5    Frank   NaN  75.0       Pune
6    Grace  21.0   NaN      Delhi
7    Henry   NaN   NaN        NaN
8      Ivy  23.0  92.0  Bangalore
9     Jack   NaN   NaN    Chennai

In [25]:
values = {0:1,1:100,2:200,3:300}

In [26]:
df.fillna(value = values)

         0      1      2          3
0    Alice   20.0   85.0        300
1      Bob  100.0   90.0      Delhi
2  Charlie   19.0  200.0        300
3    David  100.0  200.0     Mumbai
4     Emma   22.0   88.0        300
5    Frank  100.0   75.0       Pune
6    Grace   21.0  200.0      Delhi
7    Henry  100.0  200.0        300
8      Ivy   23.0   92.0  Bangalore
9     Jack  100.0  200.0    Chennai

In [27]:
df

         0     1     2          3
0    Alice  20.0  85.0        NaN
1      Bob   NaN  90.0      Delhi
2  Charlie  19.0   NaN        NaN
3    David   NaN   NaN     Mumbai
4     Emma  22.0  88.0        NaN
5    Frank   NaN  75.0       Pune
6    Grace  21.0   NaN      Delhi
7    Henry   NaN   NaN        NaN
8      Ivy  23.0  92.0  Bangalore
9     Jack   NaN   NaN    Chennai